### ISSUE TITLE
Can't setup the project for contributions

### ISSUE THREAD

**Issue by mamhoff** [AlchemyCMS/alchemy-devise#21]
I actually have another issue (coming up!), but in order to provide a PR, I'd like to be able to run the current tests, but I can't. This is what happens: 

```
$ rake alchemy:spec:prepare
[Migrations...]

/home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/configuration.rb:37:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/configuration.rb:37:in `project_root_path'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/configuration.rb:28:in `application_root_path'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application.rb:246:in `loaded_application_features'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application.rb:105:in `ensure in preload'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application.rb:112:in `preload'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /home/anselm/.rvm/gems/ruby-2.1.1/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/anselm/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/anselm/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

When I remove spring from the Gemfile, the task runs through, but the tests don't run: 
```
$ rspec
/home/anselm/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:389:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

	bin/rake db:migrate RAILS_ENV=test
...

```

When I run the migrations, I get a duplicate migration error. That's a bit frustrating...

**Comment by tvdeyen** [comment]
This is (once again) an issue with the spring gem: https://github.com/rails/spring/issues/323

I will remove spring from the project.

**Comment by tvdeyen** [comment]
@mamhoff please pull and try again.

**Comment by mamhoff** [comment]
Yep, that was it! Thanks a bunch! :)
