### ISSUE TITLE
Getting undefined method `ssl_required` only on production

### ISSUE THREAD

**Issue by mamhoff** [AlchemyCMS/alchemy-devise#24]
Dear Alchemy Team, 

I can't log into my production site because of `ssl_required?` not being defined. Strangely, this does not happen in the development environment. Where does that method come from? What's happening?

Log: 
```
I, [2015-05-03T14:32:15.673792 #16797]  INFO -- : Started GET "/admin/login" for 37.120.87.253 at 2015-05-03 14:32:15 +0200
I, [2015-05-03T14:32:15.675759 #16797]  INFO -- : Processing by Alchemy::UserSessionsController#new as HTML
I, [2015-05-03T14:32:15.683792 #16797]  INFO -- : Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.0ms)
F, [2015-05-03T14:32:15.698341 #16797] FATAL -- : 
NoMethodError (undefined method `ssl_required?' for #<Alchemy::UserSessionsController:0x007f2ad0f10a20>):
  /var/www/virtual/htholen/rails/ptw/shared/bundle/ruby/2.2.0/bundler/gems/alchemy-devise-9acd927cc1e5/app/controllers/alchemy/user_sessions_controller.rb:6:in `block in <class:UserSessionsController>'
  activesupport (4.2.1) lib/active_support/callbacks.rb:446:in `instance_exec'
  activesupport (4.2.1) lib/active_support/callbacks.rb:446:in `block in make_lambda'
  activesupport (4.2.1) lib/active_support/callbacks.rb:145:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
```

**Comment by tvdeyen** [comment]
It's defined in https://github.com/AlchemyCMS/alchemy_cms/blob/master/app/controllers/alchemy/base_controller.rb#L80

Since 3.1 we don't patch the `ApplicationController` anymore and the `Alchemy::UserSessionsController` inherits from `Devise::UserSessionsController`. To fix this, we need to tell Devise to inherit from `Alchemy::BaseController` or extract the `ssl_required?` and alike methods into a module that we can extend the `Alchemy::UserSessionsController` with. 

I prefer the second option.

Would you send a pull request?

**Comment by mamhoff** [comment]
PR sent! :)

**Comment by tvdeyen** [comment]
Pull request merged. Thank you!
